
cw_env: prod
cw_geo: lga1

modelServer:
  name: "neurips-model-image"
  # Model Training
  # 4090
  # image: "{docker_registry}/{image_name}"
  # tag: "2"
  # Model Eval
  # 4090
  image: "4090_eval"
  tag: "3"
  # A100
  # image: "{docker_registry}/{image_name}"
  # tag: "1"
  gpus: 1
  memory: "64Gi"
  cpus: 8

helmServer:
  name: "neurips-helm-image"
  # Change to include eval repo prefix when image is built
  image: "{docker_registry}/helm-server" 
  tag: "2"
  memory: "64Gi"
  cpus: 8
 
imagePullPolicy: "IfNotPresent"

