apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
     matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.modelServer.name }}
          image: "{{ tpl .Values.modelServer.image . }}:{{ tpl .Values.modelServer.tag . }}"
          imagePullPolicy: "{{ tpl .Values.imagePullPolicy . }}"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            limits:
              cpu: {{ .Values.modelServer.cpus }}
              memory: {{ .Values.modelServer.memory }}
              {{- if .Values.modelServer.gpus }}
              nvidia.com/gpu: {{ .Values.modelServer.gpus }}
              {{ end }}
        - name: {{ .Values.helmServer.name }}
          image: "{{ tpl .Values.helmServer.image . }}:{{ tpl .Values.helmServer.tag . }}"
          imagePullPolicy: "{{ tpl .Values.imagePullPolicy . }}"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            limits:
              cpu: {{ .Values.helmServer.cpus }}
              memory: {{ .Values.helmServer.memory }}
          volumeMounts:
            - mountPath: /mnt/shared
              name: shared-data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{ if .Values.modelServer.gpus }}
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_NVLINK_80GB
              {{ end }}
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - {{ upper .Values.cw_geo }}
